# Generated by Django 4.2.1 on 2023-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('money', models.IntegerField(blank=True, default=0)),
                ('popularity', models.IntegerField(blank=True, default=0)),
                ('army', models.IntegerField(blank=True, default=0)),
                ('land', models.IntegerField(blank=True, default=0)),
                ('rare', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'db_table': 'cards',
                'managed': True,
            },
        ),
    ]
