# Generated by Django 4.2.1 on 2023-05-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Num_edu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_num', models.IntegerField(blank=True, default=0)),
                ('error', models.FloatField(blank=True, default=0)),
                ('graph', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'db_table': 'models',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trys',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_num', models.IntegerField(blank=True, default=0)),
                ('dif_money', models.IntegerField(blank=True, default=0)),
                ('dif_popularity', models.IntegerField(blank=True, default=0)),
                ('dif_army', models.IntegerField(blank=True, default=0)),
                ('dif_land', models.IntegerField(blank=True, default=0)),
                ('num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.num_edu')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'db_table': 'trys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solutions', models.TextField(blank=True, default='')),
                ('Try', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trys')),
            ],
            options={
                'verbose_name': 'Король',
                'verbose_name_plural': 'Короли',
                'db_table': 'kings',
                'managed': True,
            },
        ),
    ]
