# Generated by Django 4.2.1 on 2023-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_num_edu_trys_kings'),
    ]

    operations = [
        migrations.AddField(
            model_name='num_edu',
            name='dif_army',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='num_edu',
            name='dif_land',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='num_edu',
            name='dif_money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='num_edu',
            name='dif_popularity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
