# Generated by Django 4.2.1 on 2023-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_num_edu_dif_army_num_edu_dif_land_num_edu_dif_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='num_edu',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
