# Generated by Django 4.2.1 on 2023-05-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_num_edu_dif_army_alter_num_edu_dif_land_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='num_edu',
            old_name='epoth',
            new_name='epo',
        ),
    ]
