# Generated by Django 4.2.1 on 2023-05-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_num_edu_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='num_edu',
            name='graph',
        ),
    ]
