# Generated by Django 4.2.1 on 2023-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_num_edu_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='graph',
            field=models.TextField(default=[0]),
        ),
    ]
