# Generated by Django 4.2.1 on 2023-05-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cards_graph_alter_cards_rare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='graph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='rare',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
