# Generated by Django 4.2.1 on 2023-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cards_graph_alter_cards_rare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='graph',
        ),
        migrations.AddField(
            model_name='num_edu',
            name='graph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
