# Generated by Django 4.2.1 on 2023-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_cards_graph_num_edu_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='num_edu',
            name='graph_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
