# Generated by Django 4.2.1 on 2023-05-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_num_edu_graph_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='trys',
            name='epo',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='trys',
            name='graph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trys',
            name='graph_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
