# Generated by Django 4.2.1 on 2023-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_trys_epo_trys_graph_trys_graph_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='trys',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
